### PR TITLE
Issue 36 query bonds import

### PR DESCRIPTION
**Pull request by JonasSchaub**
Fixed the import without adding implicit hydrogen atoms and revised the exception handling of the import routines

### CODE REVIEW

**Comment by JonasSchaub** [comment]
Reference issue #36

**Comment by JonasSchaub** [comment]
@FelixBaensch please check whether this corresponds with your expectations now.

**Comment by FelixBaensch** [comment]
This cannot meet my expectations, as the MDLV3000 reader does not support bondtypes > 4:
https://github.com/cdk/cdk/issues/1061

But I will have a look

**Comment by JonasSchaub** [comment]
Please try MDLV2000 exclusively, then :D

**Comment by FelixBaensch** [comment]
Added comment in #36

**Pull request merged**
